#                                                                                 ,----,                                                                                        
#           ____                   ,--.          ,-.----.                       ,/   .`|       ,--,                       ,----..            ,--.                               
#         ,'  , `.   ,---,       ,--.'|    ,---,.\    /  \     ,---,          ,`   .'  :     ,--.'|          ,----..     /   /   \         ,--.'|    ,---,.   ,---,  ,----..    
#      ,-+-,.' _ |,`--.' |   ,--,:  : |  ,'  .' ||   :    \   '  .' \       ;    ;     /  ,--,  | :         /   /   \   /   .     :    ,--,:  : |  ,'  .' |,`--.' | /   /   \   
#   ,-+-. ;   , |||   :  :,`--.'`|  ' :,---.'   ||   |  .\ : /  ;    '.   .'___,/    ,',---.'|  : '        |   :     : .   /   ;.  \,`--.'`|  ' :,---.'   ||   :  :|   :     :  
#  ,--.'|'   |  ;|:   |  '|   :  :  | ||   |   .'.   :  |: |:  :       \  |    :     | |   | : _' |        .   |  ;. /.   ;   /  ` ;|   :  :  | ||   |   .':   |  '.   |  ;. /  
# |   |  ,', |  ':|   :  |:   |   \ | ::   :  |-,|   |   \ ::  |   /\   \ ;    |.';  ; :   : |.'  |        .   ; /--` ;   |  ; \ ; |:   |   \ | ::   :  :  |   :  |.   ; /--`   
# |   | /  | |  ||'   '  ;|   : '  '; |:   |  ;/||   : .   /|  :  ' ;.   :`----'  |  | |   ' '  ; :        ;   | ;    |   :  | ; | '|   : '  '; |:   |  |-,'   '  ;;   | ;  __  
# '   | :  | :  |,|   |  |'   ' ;.    ;|   :   .';   | |`-' |  |  ;/  \   \   '   :  ; '   |  .'. |        |   : |    .   |  ' ' ' :'   ' ;.    ;|   :  ;/||   |  ||   : |.' .' 
# ;   . |  ; |--' '   :  ;|   | | \   ||   |  |-,|   | ;    '  :  | \  \ ,'   |   |  ' |   | :  | '        .   | '___ '   ;  \; /  ||   | | \   ||   |   .''   :  ;.   | '_.' : 
# |   : |  | ,    |   |  ''   : |  ; .''   :  ;/|:   ' |    |  |  '  '--'     '   :  | '   : |  : ;        '   ; : .'| \   \  ',  / '   : |  ; .''   :  '  |   |  ''   ; : \  | 
# |   : '  |/     '   :  ||   | '`--'  |   |    \:   : :    |  :  :           ;   |.'  |   | '  ,/         '   | '/  :  ;   :    /  |   | '`--'  |   |  |  '   :  |'   | '/  .' 
# ;   | |`-'      ;   |.' '   : |      |   :   .'|   | :    |  | ,'           '---'    ;   : ;--'          |   :    /    \   \ .'   '   : |      |   :  \  ;   |.' |   :    /   
# |   ;/          '---'   ;   |.'      |   | ,'  `---'.|    `--''                      |   ,/               \   \ .'      `---`     ;   |.'      |   | ,'  '---'    \   \ .'    
# '---'                   '---'        `----'      `---`                               '---'                 `---`                  '---'        `----'              `---`      
                                                                                                                                                                              


#Should the plugin be enabled
enabled: true

#Should the plugin be loaded as an Economy provider
vaultEnabled: true

# The location of the sqlite db
sqliteLocation: plugins/MinePath/MinePath.db
# The db type (sqlite, mysql, postgresql)
dbType: mysql
# The hostname of the database
dbHost: localhost
# The port of the database
dbPort: 3306
# The database name (if it doesn't exist the plugin will error out when using non-sqlite dbType)
dbName: minepath
# The database table
dbTable: balance
# The database username
dbUsername: root
# The database password (mysql default root password is no password, you should change it)
dbPassword:
# Should the JDBC (non-sqlite) connection use SSL
dbUseSSL: false
external-db:
  url: jdbc:mysql://localhost:3306/minecraft
  user: root
  password: 
# The PublicKey of the token which should be used
tokenMint: 
# The private key used to sign the transactions (must be base58 encoded)
# To get this, use the wallet Phantom (https://phantom.app)
# In phantom, click the settings gear at the bottom of the screen --> click "Export Private Key" --> Copy and paste the text into the "signer" field.
# This key is never shared and never leaves your server.
signer:
# The PublicKey associated with the signer
publicKey: 
# The URL of the RPC you want to connect to
rpcURL: 
# Currency Symbol
currencySymbol: MINE
# Path‐token on–chain credentials
pathSigner: 
pathPublicKey: 
pathMint: 
# conversion rate: 100 mine == 1 path
pathRate: 100.0

# Starting balance of a new player
startingBalance: 0.0
# The minimum amount a player is allowed to export
minimumExport: 0.5
# How often can a player try to export or view the server balance in seconds
requestLimitPerSecond: 1
