  name: MinePath
  main: com.solanacoin.MinePathCoinPlugin
  author: HungPhan0612
  version: 1.0.0
  api-version: 1.18
  softdepend:
    - Vault
  permissions:

    minepath.*:
      description: Allows for all commands
      default: op
      children:
        minepath.balance: true
        minepath.db: true
        minepath.lbh: true
        minepath.send: true
        minepath.admin: true
        minepath.help: true
        minepath.buy: true
        minepath.authorize: true
        minepath.burn: true
        minepath.claim: true

    minepath.user:
      description: Allows to check balance, export, and send
      default: not op
      children:
        minepath.db: false
        minepath.lbh: false
        minepath.admin: false
        minepath.balance: true
        minepath.send: false
        minepath.help: true
        minepath.buy: false
        minepath.authorize: true
        minepath.burn: false
        minepath.claim: false

  commands:
    tokenclaim:
      description: Claim the token to your account.
      permission: minepath.claim
      permission-message: You do not have permission!
  
    tokenauthorize:
       description: Authorize the session key first time.
       permission: minepath.authorize
       permission-message: You do not have permission!

    tokenburn:
      description: Burn the token to get the balance in the game.
      permission: minepath.burn
      permission-message: You do not have permission!
      
    tokenhelp:
      description: "Show help for MinePathCoinPlugin commands"
      permission: minepath.help
      usage: /<command>

    
    tokenbalance:
      description: Check your balance
      aliases:
        - bal
        - sbalance
        - cbalance
        - sbal
        - cbal
      permission: minepath.balance
      permission-message: You do not have permission!
      usage: /<command>

    tokendb:
      description: Manage the db connection
      aliases:
        - sdb
        - cdb
      permission: minepath.db
      permission-message: You do not have permission!
      usage: /<command> connect|disconnect|status

    tokenlbh:
      description: Get the latest blockhash
      aliases:
        - slbh
        - clbh
      permission: minepath.lbh
      permission-message: You do not have permission!
      usage: /<command>

    tokensend:
      description: Send from your balance to another player
      aliases:
        - pay
        - ssend
        - csend
      permission: minepath.send
      permission-message: You do not have permission!
      usage: /<command> [player] [amount] confirm
    tokenbuy:
      permission: minepath.buy
      permission-message: You do not have permission!
      usage: /<command> [amount] confirm
    tokenadmin:
      description: Administrator commands
      aliases:
        - sadmin
        - cadmin
      permission: minepath.admin
      permission-message: You do not have permission!
      usage: |
             /<command> balance|add|subtract|delete|set|destroydb
             Example: /<command> add [player] [amount] - add x amount to the player's balance
             Example: /<command> balance - get the your's balance
             Example: /<command> balance [player] - get a player's balance
             Example: /<command> reload - reload this plugins' config
             Example: /<command> destroydb confirm - delete all entries from the db
